# Generated by Django 3.2.10 on 2021-12-23 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=500)),
                ('type', models.IntegerField(choices=[(1, 'Followers'), (2, 'Everyone')], default=1)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('receivers', models.ManyToManyField(related_name='received_notifications', to='profile.UserProfile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='profile.employeeprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
