# Generated by Django 3.2.8 on 2021-11-12 06:12

import core.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to=core.models.Image.get_file_path,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_ppoi",
            field=versatileimagefield.fields.PPOIField(
                blank=True,
                default="0.5x0.5",
                editable=False,
                max_length=20,
                null=True,
            ),
        ),
    ]
