# Generated by Django 3.2.10 on 2021-12-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211112_0942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
