# Generated by Django 3.2.10 on 2021-12-31 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20211231_1255'),
        ('category', '0002_category_is_active'),
        ('core', '0003_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('establishment_date', models.DateTimeField(null=True)),
                ('worker_count', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('full_address', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('rate', models.FloatField(null=True)),
                ('rate_count', models.IntegerField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='category.category')),
                ('images', models.ManyToManyField(blank=True, related_name='businesses', to='core.Image')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='profile.employeeprofile')),
            ],
        ),
    ]
