# Generated by Django 3.2.10 on 2022-01-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211231_1255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
