# Generated by Django 3.2.10 on 2021-12-31 12:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0005_auto_20211231_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('token', models.CharField(max_length=12)),
                ('reference_code', models.CharField(max_length=24)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('filters', models.JSONField()),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profile.userprofile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profile.employeeprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
