# Generated by Django 3.2.8 on 2021-12-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
