# Generated by Django 3.2.8 on 2021-11-12 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0003_auto_20211112_1631"),
        ("reserve", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_reserves",
                to="profile.employeeprofile",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="participated_reserves",
                to="profile.UserProfile",
            ),
        ),
    ]
