# Generated by Django 3.2.8 on 2021-11-04 06:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reserve", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="participated_reserves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
