# Generated by Django 3.2.8 on 2021-11-09 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="bib",
            field=models.TimeField(
                default=datetime.datetime(2021, 11, 9, 19, 59, 6, 534046)
            ),
        ),
    ]
